---
#
# Playbook to install the ELK stack + Beats
#
- hosts: node
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: logstash }
  - { role: kibana }
  - { role: metricbeat }
  - { role: some-data }
  - { role: restart-services }
